Guts/mkdocs-rss-plugin

- mkdocs_rss_plugin/templates/rss.xml.jinja2
- mkdocs_rss_plugin/util.py
As spotted in #9, image's length is missing to perfectly comply with RSS specification about enclosures.
With this PR:
- determine if referenced image in meta tags is local or remote
- if local, use `pathlib.path.stat().st_size()` to get content length
- if remote, perform a HTTP request:
- a HEAD request is performed
- if failing, a GET request is performed with disabled SSL verification
- if still failing --> `None`
- the calculated length is added into the final XML
Close #9.
> Compliance: handle images length

- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/templates/rss.xml.jinja2
- mkdocs_rss_plugin/util.py
- enable auto-escape on feed and item titles, using the [Jinja `e` filter](https://jinja.palletsprojects.com/en/2.11.x/templates/#working-with-manual-escaping) - #19
- improve consistency for missing attributes in mkdocs.yml, returning almost always a `None` value
> Handle special characters and different cases

- CHANGELOG.md
- README.md
- docs/usage/configuration.md
- docs/usage/index.md
- mkdocs.yml
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/templates/rss.xml.jinja2
- tests/test_config.py
Add an option `pretty_print` to restore former behavior and prevent eventual side-effects.
Close #18 
```xml
<?xml version="1.0" encoding="UTF-8" ?><rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/"> <channel><title>MkDocs RSS Plugin</title><description>Documentation about the MkDocs RSS Plugin</description><link>https://guts.github.io/mkdocs-rss-plugin/</link><atom:link href="https://guts.github.io/mkdocs-rss-plugin/feed_rss_created.xml" rel="self" type="application/rss+xml" /><managingEditor>dev@ingeoveritas.com (Julien M.)</managingEditor><docs>https://github.com/guts/mkdocs-rss-plugin/</docs><language>en</language> <pubDate>Tue, 05 Jan 2021 12:03:26 -0000</pubDate> <lastBuildDate>Tue, 05 Jan 2021 12:03:26 -0000</lastBuildDate> …
```
> Feed XML output improvments

- docs/usage/configuration.md
- docs/usage/index.md
- mkdocs_rss_plugin/customtypes.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/templates/rss.xml.jinja2
- mkdocs_rss_plugin/util.py
Closes #34.
Retrieve git contributors will arrive in a next step.
> Retrieve author or authors from page.meta

- .gitignore
- docs/usage/configuration.md
- mkdocs_rss_plugin/customtypes.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- tests/test_config.py
I was experimenting @rmorshea's great contribution on #43 to include only a small subset of relevant pages in the feeds for my site, hoping that it would be an elegant way to overcome the limitation in #23. However, I noticed the following:
- The plugin was still outputting warnings because it failed to obtain the correct Git dates from pages that I was excluding with `match_path`
- None of the pages that I was including with `match_path` would show up on the output
This was because the `match_path` filter was only being applied during the `on_post_build` event handler, and [after the list of pages to include in the output had already been truncated](https://github.com/Guts/mkdocs-rss-plugin/blob/master/mkdocs_rss_plugin/util.py#L479-L480) by the configuration `length`.
To fix this issue …
> fix: Completely skip pages excluded by match_path

- docs/schema.json
- mkdocs.yml
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/timezoner_pre39.py
- mkdocs_rss_plugin/timezoner_py39.py
- mkdocs_rss_plugin/util.py
- requirements/base.txt
- tests/fixtures/mkdocs_complete.yml
- tests/test_timezoner.py
Example:
```yaml
- rss:
date_from_meta:
as_creation: "date"
as_update: false
datetime_format: "%Y-%m-%d %H:%M"
default_timezone: "Europe/Paris"
```
Defaults to UTC.
Closes #133
> Feature: add option to set default timezone

- mkdocs_rss_plugin/util.py
- tests/fixtures/docs/page_with_meta_no_creation_date.md
- tests/test_build.py
Until now, when a page has no creation or update date (in meta and in git log), the plugin fallbacks on build timestamp for both.
This PR makes it more granular:
- if only the creation date is missing, so it uses the build timestamp only for this one
- if only the update date is missing, so it uses the build timestamp only for this one
> Improvment: more granular fallback to build timestamp

- requirements/base.txt
Considering the discussion in #137, let's raises the upper Mkdocs version.
For now, I set the major version to not break anything.
Later, if everything still goes well after some new Mkdocs versions released, I would remove it completely.
> Set Mkdocs upper cap to major version

- mkdocs_rss_plugin/plugin.py
- tests/fixtures/docs/page_with_meta_draft_true.md
Hi @hellt,
Can you have a test from here please?
Close #147
> Feature: ignore pages with draft:true in meta

- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- tests/fixtures/mkdocs_pretty_print_disabled.yml
- tests/fixtures/mkdocs_pretty_print_enabled.yml
If `site_url` is not set in `mkdocs.yml`, the plugin was crashing the mkdocs build.
Now it log an error message when config is loaded AND every times an URL is built BUT not interrupts the build.
> Improve: handle missing site url

- mkdocs_rss_plugin/util.py
Not really a good idea because it breaks the feed compliance but a tool is about to respect its user choices!
> Handle abstract_chars_count set to 0

- .github/workflows/lint-and-tests.yml
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- tests/fixtures/mkdocs_complete_no_git.yml
- tests/test_build_no_git.py
- tests/test_config.py
Add option `use_git`, defaults to True.
If not, the plugin does not try use the git log nor does not check if this is a valid git repository and use only informations from page meta (YAML frontmatter).
Closes #160
> Add option to enable/disable git use.

- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
> Road to Mkdocs 1.4: use  config attributes

- docs/configuration.md
- docs/index.md
- docs/integrations.md
- docs/schema.json
- mkdocs.yml
- mkdocs_rss_plugin/config.py
- mkdocs_rss_plugin/integrations/theme_material_social_plugin.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- requirements/testing.txt
- setup.py
- tests/fixtures/mkdocs_item_image_social_cards_enabled_site.yml
- tests/fixtures/mkdocs_item_image_social_enabled_but_cards_disabled.yml
- tests/test_config.py
- tests/test_integrations_material_social_cards.py
- tests/test_rss_util.py
This PR adds logic and option to support Social Cards of Material theme out-of-the-box.
Considering the RSS feed from this plugin documentation: <https://guts.github.io/mkdocs-rss-plugin/integrations/>
```xml
<item>
<title>Integrations</title>
<description>&lt;h2&gt;Reference RSS feeds in HTML meta-tags&lt;/h2&gt;
&lt;p&gt;To facilitate the discovery of RSS feeds, it&#39;s recommended to add relevant meta-tags in &lt;code&gt;&amp;lt;head&amp;gt;&lt;/code&gt; section in HTML pa...&lt;/p&gt;</description>
<link>https://guts.github.io/mkdocs-rss-plugin/integrations/?utm_source=documentation&amp;utm_medium=RSS&amp;utm_campaign=feed-syndication</link>
<pubDate>Tue, 12 Dec 2023 11:02:08 +0100</pubDate>
<source url="https://guts.github.io/mkdocs-rss-plugin/feed_rss_created.xml">MkDocs RSS …
```
> Feature: support material social cards plugin

- mkdocs_rss_plugin/constants.py
- mkdocs_rss_plugin/git_manager/ci.py
- mkdocs_rss_plugin/integrations/theme_material_social_plugin.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/timezoner_pre39.py
- mkdocs_rss_plugin/timezoner_py39.py
- mkdocs_rss_plugin/util.py
See: https://www.mkdocs.org/dev-guide/plugins/#logging-in-plugins
> feature:  use plugin logger as recomended by Mkdocs (road to Mkdocs>=1.4)

- mkdocs_rss_plugin/util.py
If the social card has been previously published, it works.
> improvement: if social card not found, try to retrieve length from remote URL

- docs/index.md
Nested lists require 4 spaces of indent in Python Markdown, which differs from GitHub Flavored Markdown.
This PR fixes the indent in https://guts.github.io/mkdocs-rss-plugin/#credits.
Relates-to: https://github.com/Python-Markdown/markdown/issues/3
Besides, `rg '  -' ./docs/ --type=md --context 5` finds another nested list, but its indentation is correct.
https://github.com/Guts/mkdocs-rss-plugin/blob/8935f6c6552e7b7eec19828b2f24473ebe05f3ca/docs/configuration.md#L416-L418
> docs: fix indentation of nested lists

- docs/configuration.md
`locale` at root was deprecated in #212, and `theme/language` only works for Material theme.
Relevant implementation:
https://github.com/Guts/mkdocs-rss-plugin/blob/15938261138769919c714e60d4925c58bffa81e1/mkdocs_rss_plugin/util.py#L720-L723
> Update docs on locale configuration

- docs/configuration.md
- mkdocs_rss_plugin/util.py
- tests/fixtures/docs/page_without_meta_early_delimiter.md
- tests/fixtures/mkdocs_item_delimiter_empty.yml
- tests/test_build.py
Patches sent by mail by @tiosgz. Applied with `git am`. It's my  very first time in this kind of [git email workflow](https://git-send-email.io/). Pfiu !.
Command used:
```sh
git am --3way --ignore-space-change v2-0001-fix-retrieving-article-description.patch
git am --3way --ignore-space-change v2-0002-docs-configuration-fix-update-abstract_-chars_cou.patch
git am --3way --ignore-space-change v2-0003-tests-add-test-cases-for-abstract_delimiter.patch
```
Supersedes https://github.com/Guts/mkdocs-rss-plugin/pull/202
cc @craigbox  @YDX-2147483647
> Fix: abstract limit

- .github/workflows/release.yml
Upstream reference: https://docs.pypi.org/trusted-publishers/
> ci: use trusted publisher and remove token

- mkdocs_rss_plugin/plugin.py
- tests/base.py
- tests/dev/dev_load_config.py
- tests/fixtures/docs/blog/posts/sample_blog_post.md
- tests/fixtures/mkdocs_multiple_instances.yml
- tests/test_build.py
It's now possible to have a mkdocs.yml like this:
```yaml
plugins:
- rss
- rss:
feeds_filenames:
json_created: blog.json
json_updated: blog-updated.json
rss_created: blog.xml
rss_updated: blog-updated.xml
match_path: "blog/.*"
```
Closes #219
> feature: allow multiple instances

- .github/workflows/lint-and-tests.yml
- .pre-commit-config.yaml
- mkdocs_rss_plugin/integrations/theme_material_social_plugin.py
- mkdocs_rss_plugin/models.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- setup.py
- sonar-project.properties
- tests/test_build.py
Since some advanced types operations introduced in mkdocs>=1.5 are not entirely supported by Python 3.8 and 3.9, let's switch to 3.10 as minimal version:
Logs with failing error in #285 (https://github.com/Guts/mkdocs-rss-plugin/actions/runs/9450849461/job/26030426819?pr=285):
> FAILED tests/test_build.py::TestBuildRss::test_simple_build_custom_output_basename - TypeError: Subscripted generics cannot be used with class and instance checks
```python
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mkdocs/plugins.py:96: in load_config
return self.config.validate()
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/mkdocs/config/base.py:231: in validate
run_failed, run_warnings = self._validate()
/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packa …
```
> Chore: set minimal python version to 3.10

- mkdocs_rss_plugin/util.py
- requirements/base.txt
> Fix remote image length warnings using requests instead of urllib (standard lib)

- mkdocs_rss_plugin/config.py
- mkdocs_rss_plugin/plugin.py
> fix(config): do not raise error for bad date_from_meta.default_time value and fallback to default

- docs/configuration.md
- mkdocs_rss_plugin/config.py
- mkdocs_rss_plugin/constants.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- requirements/base.txt
- tests/dev/dev_cached_http.py
- tests/test_config.py
This PR aims to improve plugin's performance regarding HTTP requests which are performed to retrieve remote image length:
- add a new option `cache_dir`
- rely on https://pypi.org/project/CacheControl/ to manage local cache requests
For now, it works only for GET requests. See upstream issue: https://github.com/psf/cachecontrol/issues/337
> Feature: add http caching mechanism

- docs/configuration.md
- mkdocs_rss_plugin/util.py
- tests/fixtures/docs/page_with_meta_override_rss_description.md
- tests/test_build.py
Hello @Guts 
Thanks for the awesome project.
I use this plugin heavily in my [SRE blog](https://developer-friendly.blog).
I figured it would be nice to allow per page customization of the `description` field, cause at the moment, there's not a lot one can do when the description before `` is short and extra detail is desired.
With this change, you can have separate contents for RSS description and your typical content.
An example taken from the [Material for Mkdocs Social Cards](https://squidfunk.github.io/mkdocs-material/plugins/social/#option.description):
```markdown
---
date: 2024-06-24
description: >-
This is the SEO description.
social:
cards_layout_options:
description: >-
This is the social cards description.
rss:
feed_description: >-
And I want to have customized RSS description. …
```
> feat: allow per-page description customization

- mkdocs_rss_plugin/plugin.py
`page.file.src_path` on Windows contains backslashes resulting in an empty RSS feed if `match_path` contains a forward slash. This commit replaces `src_path` with `src_uri` which provides an OS independent path with forward slashes '/'.
fixes #321
> Make match_path OS agnostic

- mkdocs_rss_plugin/integrations/theme_material_base.py
- mkdocs_rss_plugin/integrations/theme_material_blog_plugin.py
- mkdocs_rss_plugin/integrations/theme_material_social_plugin.py
- tests/fixtures/mkdocs_items_material_blog_enabled.yml
- tests/test_integrations_material.py
- tests/test_integrations_material_blog.py
- tests/test_integrations_material_social_cards.py
Related to https://github.com/Guts/mkdocs-rss-plugin/issues/250
> refacto(material_integrations): use POO to manage integrations with Material theme framework

- README.md
- docs/configuration.md
- mkdocs_rss_plugin/config.py
- mkdocs_rss_plugin/integrations/theme_material_base.py
- mkdocs_rss_plugin/plugin.py
- mkdocs_rss_plugin/util.py
- tests/fixtures/mkdocs_items_material_blog_enabled.yml
- tests/test_config.py
Related to https://github.com/Guts/mkdocs-rss-plugin/issues/250
> feature(integration): make the integration with Material Blog configurable through an option

- docs/integrations.md
- mkdocs_rss_plugin/integrations/theme_material_base.py
- mkdocs_rss_plugin/integrations/theme_material_blog_plugin.py
- mkdocs_rss_plugin/integrations/theme_material_social_plugin.py
- mkdocs_rss_plugin/util.py
- tests/fixtures/docs/blog/.authors.yml
- tests/fixtures/docs/blog/posts/firstpost.md
- tests/fixtures/mkdocs_items_material_blog_enabled_but_integration_disabled.yml
- tests/test_integrations_material_blog.py
Related to: https://github.com/Guts/mkdocs-rss-plugin/issues/250
> Feature: use author name and email from `.authors.yml` set up in Material Blog

- mkdocs_rss_plugin/integrations/theme_material_blog_plugin.py
Related to: https://github.com/Guts/mkdocs-rss-plugin/issues/250
See: https://validator.w3.org/feed/docs/error/InvalidContact.html
Before:
```xml
<author>John Doe (John.Doe@example.com)</author>
```
After:
```xml
<author>John.Doe@example.com (John Doe)</author>
```
cc @stefansli
> fix(rss): email and name were inverted in output and so uncompliant

- requirements/testing.txt
see: https://github.com/lukasschwab/jsonfeed/issues/15
> fix(upstream): force jsonfeed-util version since it uses a non Python 3.9 syntax, breaking lint and tests

- mkdocs_rss_plugin/integrations/theme_material_social_plugin.py
- tests/fixtures/mkdocs_item_image_social_cards_blog_directory_url_disabled.yml
- tests/test_integrations_material_social_cards.py
This should fix #319 
The path building is based on https://github.com/squidfunk/mkdocs-material/blob/396c493f4774fa0bafeada5d0b555d02193557e8/src/plugins/social/plugin.py#L339-L362
> fix(material_social): use cards_dir to build cards url for page

- mkdocs_rss_plugin/util.py
When this plugin is run on a doc site that also uses the social plugin, fetching remote image data can fail. This results in a crash when building the documentation:
File "/path/installs/python/3.11.5/lib/python3.11/site-packages/mkdocs_rss_plugin/util.py", line 608, in get_image
img_length = self.get_remote_image_length(image_url=img_url)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/path/installs/python/3.11.5/lib/python3.11/site-packages/mkdocs_rss_plugin/util.py", line 710, in get_remote_image_length
return int(img_length)
^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
This patch simply returns None if `img_length` is `None.`
Closes: #369
Closes: #353
> fix: return None if remote image length is unavailable

- mkdocs_rss_plugin/plugin.py
- tests/test_build.py
Instead of stripping out the newlines characters, leading to mangled content when rendering full contents, provide a space instead.
Fixes #186
> fix: preserve sentence structure across newlines

- mkdocs_rss_plugin/git_manager/ci.py
> fix(logs): update references hyperlinks for git depth logs
